version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "phial-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18zqwx9fzmcyl"
s3_prefix = "phial-sam"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
